### PR TITLE
Expanded README.md

### PR DESCRIPTION
**Pull request by samGPU**
# Checklist ✅
- [x] I've read [CONTRIBUTIONS.md](https://github.com/scroll-tech/contribute-to-scroll/blob/main/CONTRIBUTIONS.md) document
- [x] I've filled the `contributions.json` file

# Contributor social handles (Github / Twitter / Telegram) 🎙️
   - Github: [samgpu](https://github.com/samgpu)
   - Twitter: [samgpu](https://twitter.com/samgpu)

# Contribution Description 📝
The README.md file lacked context on what this repo is for. By adding additional context about Scroll, it will make it easier for developers to utilise this repo and contribute to the ecosystem.

### CODE REVIEW

**Comment by Turupawn** [comment]
Hello @samGPU thanks for your contribution! We should be able to merge your contribution once you resolve my comments. Lmk if you have any questions or comments.

**Comment by samGPU** [comment]
Hey @Turupawn, I saw that my error was with the format of the contributions.json file and have fixed this now. Thanks for your guidance.

**Comment by Turupawn** [comment]
Hey @samGPU the contributions.json file looks good now! However I we should remove the "Why Scroll" section, please review my other comment.

**Comment by samGPU** [comment]
@Turupawn I've removed the "Why Scroll" section as you have suggested. I'm actually struggling to find any comments that you have left? I've searched through all of the conversations panels that I know exist and can't see any, I'm wondering if it could be a privacy setting restricting what I can and others can see?

**Comment by Turupawn** [comment]
What I meant was that `application and tools. You can learn` is the only change that could be considered an improvement as this repo is not meant to explain what Scroll is (the scroll.io website is). I'll close this PR to clean the PR list. Feel free to try again by fixing the conflicts and reopening.

**Pull request closed without merging**
